version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vpn-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vpn-manager:
    image: maximylis/vpn-manager:latest
    container_name: vpn-manager
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/lib/vpn-manager:/var/lib/vpn-manager

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    image: maximylis/vpn-backend:latest
    container_name: vpn-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      vpn-manager:
        condition: service_healthy
    expose:
      - "8000"

  bot:
    image: maximylis/vpn-bot:latest
    container_name: vpn-bot
    restart: unless-stopped
    env_file:
      - .env

    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: vpn_bot_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  postgres_data:
  vpn_manager_state:
