version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vpn-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vpn-manager:
    image: maximylis/vpn-manager:latest
    container_name: vpn-manager
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/lib/vpn-manager:/var/lib/vpn-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    image: maximylis/vpn-backend:latest
    container_name: vpn-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - "8000:8000"
    depends_on:
      - postgres
      - vpn-manager

  bot:
    image: maximylis/vpn-bot:latest
    container_name: vpn-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  postgres_data:
  vpn_manager_state:
